name: Lint Code Base
on: [pull_request]

jobs:
  package-analysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: axel-op/dart-package-analyzer@v3
        with:
          # Required:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - run: flutter format --set-exit-if-changed .